name: Run Test + Build Script
on: push

jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo Code
      uses: actions/checkout@v1

    - name: Run Package Builder
      run: sh ./build.sh


    - name: Run Package Tester
      run: sh ./test.sh